apiVersion: v1
kind: Service
metadata:
  namespace: maismilhas
  name: jenkins
spec:
  type: NodePort
  ports:
    - port: 8080
      targetPort: 8080
  externalIPs:
  - 40.87.91.96    
  selector:
    app: jenkins